//! 生成与合并：API 聚合生成、根 init.lua 渲染、入口合并（分界标记）、
//! emmyrc/gitignore 合并、AGENTS.md 同步

use super::rewrite;
use super::{code_set_dir, LogFn};
use crate::config::BgdConfig;
use anyhow::Result;
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};

const API_AGG_HEADER: &str = "-- AUTO-GENERATED BY BGD_SCE_TOOLS，请勿手改";
/// 入口分界标记（标记之后为本工具生成内容）
const ENTRANCE_MARKER: &str =
    "-- ===== AUTO-GENERATED BY bgd_sce_tools（以下内容为入口合并生成，请勿直接编辑） =====";
const GITIGNORE_HEADER: &str =
    "# AUTO-GENERATED BY bgd_sce_tools，请勿手改，请编辑 .bgd/src/.gitignore";

// ---------------------------------------------------------------- API 聚合生成

/// 扫描 {libs,src}/{common,server,client}/api/*.lua，重新生成聚合 init.lua
pub fn regen_api_aggregations(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<Vec<PathBuf>> {
    let mut generated = Vec::new();
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        let root_prefix = Path::new(dir)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        for side in ["common", "server", "client"] {
            let api_dir = src_root.join(side).join("api");
            if !api_dir.is_dir() {
                continue;
            }
            let mut modules: Vec<String> = Vec::new();
            for entry in fs::read_dir(&api_dir)? {
                let entry = entry?;
                let path = entry.path();
                if path.extension().is_some_and(|e| e == "lua")
                    && path.file_name().is_some_and(|n| n != "init.lua")
                {
                    modules.push(path.file_stem().unwrap_or_default().to_string_lossy().into_owned());
                }
            }
            modules.sort();

            let ns = format!("bgd_api.{side}");
            let mut lines = vec![
                API_AGG_HEADER.to_string(),
                format!("-- 全局API聚合：api/ 目录下的每个模块自动挂载为 {ns}.<模块名>"),
            ];
            if code_set == "libs" {
                lines.push(format!("{ns} = {{}}"));
            } else {
                lines.push(format!("{ns} = {ns} or {{}}"));
            }
            for m in &modules {
                lines.push(format!("{ns}.{m} = require('{root_prefix}.{side}.api.{m}')"));
            }
            let out = api_dir.join("init.lua");
            let new_content = format!("{}\n", lines.join("\n"));
            let old = fs::read_to_string(&out).unwrap_or_default();
            if old != new_content {
                fs::write(&out, &new_content)?;
                log(&format!("[gen] api 聚合: {}", out.display()));
            }
            generated.push(out);
        }
    }
    Ok(generated)
}

// ---------------------------------------------------------------- 根 init.lua 渲染

/// code set 根的 init.lua 作为模板渲染到产物根（{{target}}/{{module}}/{{time}}）
pub fn render_root_init(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let tpl = cfg.abs(bgd_root, dir).join("init.lua");
        if !tpl.exists() {
            log(&format!("[warn] 根 init.lua 不存在: {}", tpl.display()));
            continue;
        }
        let content = fs::read_to_string(&tpl)?;
        for side in ["server", "client"] {
            let key = format!("{code_set}_{side}_target");
            let target_rel = match key.as_str() {
                "libs_server_target" => &cfg.libs_server_target,
                "libs_client_target" => &cfg.libs_client_target,
                "game_server_target" => &cfg.game_server_target,
                _ => &cfg.game_client_target,
            };
            let target = cfg.abs(bgd_root, target_rel);
            let target_name = target
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            let time_str = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs().to_string())
                .unwrap_or_default();
            let out = content
                .replace("{{target}}", &target_name)
                .replace("{{module}}", side)
                .replace("{{time}}", &time_str);
            fs::create_dir_all(&target)?;
            fs::write(target.join("init.lua"), out)?;
            log(&format!("[ok] {side}: init.lua <- {code_set}/init.lua"));
        }
    }
    Ok(())
}

// ---------------------------------------------------------------- 入口合并（分界标记）

/// 原文保留 + 标记 + 框架 entrance + 游戏 entrance。幂等。
pub fn update_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let filename = format!("{kind}.lua");
    let libs_entrance = cfg.abs(bgd_root, &cfg.libs_dir).join("entrance").join(&filename);
    let game_entrance = cfg.abs(bgd_root, &cfg.game_dir).join("entrance").join(&filename);
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);

    // entrance 内容同样要走模块名改写（引号内 libs./src. 前缀 -> 运行时根名）；
    // 行级注解跳过（rewrite_skip_annotation）在 entrance 管线同样生效
    let annotation = &cfg.rewrite_skip_annotation;
    let libs_raw = fs::read_to_string(&libs_entrance).unwrap_or_default();
    let game_raw = fs::read_to_string(&game_entrance).unwrap_or_default();
    let libs_content = rewrite::rewrite_lua(&libs_raw, kind, cfg, &rewrite::skip_ranges(&libs_raw, annotation));
    let game_content = rewrite::rewrite_lua(&game_raw, kind, cfg, &rewrite::skip_ranges(&game_raw, annotation));

    // 提取原文：含标记取标记之前；不含标记则整个现有文件视为原文（首次接入）。
    // 防御：若"原文"自身仍含标记（历史脏数据导致标记堆积），视为损坏，丢弃原文，
    // 让本次构建以空原文重新生成（一次构建即自愈）。
    let mut original = String::new();
    if dest.exists() {
        let existing = fs::read_to_string(&dest).unwrap_or_default();
        let mut candidate = match existing.find(ENTRANCE_MARKER) {
            Some(pos) => existing[..pos].to_string(),
            None => existing,
        };
        if candidate.contains(ENTRANCE_MARKER) {
            log(&format!(
                "[warn] 入口文件检测到残留标记（历史脏数据），已丢弃损坏原文并重建: {}",
                dest.display()
            ));
            candidate = String::new();
        }
        original = candidate;
    }

    let mut generated = libs_content.clone();
    if !game_content.is_empty() {
        if !libs_content.is_empty() {
            generated.push_str("\n\n-- ===== 游戏入口代码 =====\n\n");
        }
        generated.push_str(&game_content);
    }

    let mut parts: Vec<String> = Vec::new();
    if !original.trim().is_empty() {
        parts.push(original.trim_end_matches('\n').to_string());
    }
    parts.push(ENTRANCE_MARKER.to_string());
    if !generated.trim().is_empty() {
        parts.push(generated.trim_end_matches('\n').to_string());
    }
    let merged = format!("{}\n", parts.join("\n\n"));

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&dest, merged)?;
    log(&format!("[ok] entrance: {kind} -> {}", dest.display()));
    Ok(())
}

/// clean 时还原入口：删除标记及之后内容，恢复原文；无标记则不碰
pub(super) fn restore_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);
    if !dest.exists() {
        return Ok(());
    }
    let existing = fs::read_to_string(&dest).unwrap_or_default();
    if let Some(pos) = existing.find(ENTRANCE_MARKER) {
        fs::write(&dest, &existing[..pos])?;
        log(&format!("  -> 入口已还原: {}", dest.display()));
    }
    Ok(())
}

// ---------------------------------------------------------------- 配置合并生成

/// JSON 深合并：dict 递归；数组并集去重；其余 override 优先
fn deep_merge(base: &Value, over: &Value) -> Value {
    match (base, over) {
        (Value::Object(b), Value::Object(o)) => {
            let mut m = b.clone();
            for (k, v) in o {
                let merged = match m.get(k) {
                    Some(existing) => deep_merge(existing, v),
                    None => v.clone(),
                };
                m.insert(k.clone(), merged);
            }
            Value::Object(m)
        }
        (Value::Array(b), Value::Array(o)) => {
            let mut out = b.clone();
            for item in o {
                if !out.contains(item) {
                    out.push(item.clone());
                }
            }
            Value::Array(out)
        }
        (_, o) => o.clone(),
    }
}

/// libs/.emmyrc.json（base）+ src/.emmyrc.json（override）-> 项目根 .emmyrc.json
pub fn merge_emmyrc(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let libs_f = cfg.abs(bgd_root, &cfg.libs_dir).join(".emmyrc.json");
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join(".emmyrc.json");
    let base: Value = if libs_f.exists() {
        serde_json::from_str(&fs::read_to_string(&libs_f)?).unwrap_or(Value::Null)
    } else {
        Value::Null
    };
    let over: Value = if src_f.exists() {
        serde_json::from_str(&fs::read_to_string(&src_f)?).unwrap_or(Value::Null)
    } else {
        Value::Null
    };
    let merged = deep_merge(&base, &over);
    let out = bgd_root
        .parent()
        .unwrap_or(bgd_root)
        .join(".emmyrc.json");
    fs::write(&out, format!("{}\n", serde_json::to_string_pretty(&merged)?))?;
    log("[ok] merge: .emmyrc.json");
    Ok(())
}

/// libs/.gitignore + src/.gitignore -> 项目根 .gitignore（规则行去重）
pub fn merge_gitignore(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let libs_f = cfg.abs(bgd_root, &cfg.libs_dir).join(".gitignore");
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join(".gitignore");
    let mut sections: Vec<String> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for (title, f) in [("框架规则", libs_f), ("项目规则", src_f)] {
        if !f.exists() {
            continue;
        }
        let mut lines = vec![format!("# ==== {title} ====")];
        for line in fs::read_to_string(&f)?.lines() {
            let key = line.trim();
            let is_rule = !key.is_empty() && !key.starts_with('#');
            if is_rule {
                if seen.contains(key) {
                    continue;
                }
                seen.insert(key.to_string());
            }
            lines.push(line.to_string());
        }
        sections.push(lines.join("\n"));
    }
    let out = bgd_root.parent().unwrap_or(bgd_root).join(".gitignore");
    fs::write(&out, format!("{GITIGNORE_HEADER}\n\n{}\n", sections.join("\n\n")))?;
    log("[ok] merge: .gitignore");
    Ok(())
}

/// src/AGENTS.md -> 项目根 AGENTS.md（与 .gitignore 同策略：构建产物，要改就改 .bgd/src/AGENTS.md）
/// 源不存在则不动根文件；内容一致则跳过写入（避免监听触发无意义刷盘）
pub fn sync_agents_md(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join("AGENTS.md");
    if !src_f.exists() {
        return Ok(());
    }
    let out = bgd_root.parent().unwrap_or(bgd_root).join("AGENTS.md");
    let content = fs::read(&src_f)?;
    if out.exists() && fs::read(&out)? == content {
        return Ok(());
    }
    fs::write(&out, content)?;
    log("[ok] sync: AGENTS.md <- src/AGENTS.md");
    Ok(())
}
