//! 构建核心：全量构建、增量构建、清理、API 聚合生成、模板渲染、入口合并、文件监听
//! 逻辑与 Python 参考实现（.bgd/tools_py/bgd_build.py）一致。

use crate::config::BgdConfig;
use anyhow::{Context, Result};
use notify::{Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use regex::{Captures, Regex};
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

/// 日志回调：构建/监听过程产生的每一行日志
pub type LogFn<'a> = dyn Fn(&str) + Send + 'a;

const TEXT_EXTS: [&str; 4] = ["lua", "html", "css", "js"];
const API_AGG_HEADER: &str = "-- AUTO-GENERATED BY BGD_SCE_TOOLS，请勿手改";

// ---------------------------------------------------------------- 排除规则

/// rel 形如 "/server/GameServer.lua"；排除项如 "types"、"client/eg"（目录边界匹配）
pub fn is_excluded(rel: &str, excludes: &[String]) -> bool {
    let norm = format!("/{}", rel.trim_start_matches('/').replace('\\', "/"));
    for excl in excludes {
        let e = format!("/{}", excl.trim_matches(['/', '\\']).replace('\\', "/"));
        if norm == e || norm.starts_with(&format!("{e}/")) {
            return true;
        }
    }
    false
}

// ---------------------------------------------------------------- 模块名改写

/// 把引号内的源码模块名前缀改写为运行时根名：'libs.xxx' -> 'bgd_libs_server.xxx' 等
pub fn rewrite_lua(content: &str, side: &str, cfg: &BgdConfig) -> String {
    let (libs_key, game_key) = if side == "server" {
        (&cfg.libs_server_target, &cfg.game_server_target)
    } else {
        (&cfg.libs_client_target, &cfg.game_client_target)
    };
    let libs_root = Path::new(libs_key)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();
    let game_root = Path::new(game_key)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();

    let re_libs = Regex::new(r#"(['"])libs\."#).unwrap();
    let content = re_libs.replace_all(content, |caps: &Captures| {
        format!("{}{}.", &caps[1], libs_root)
    });
    let re_src = Regex::new(r#"(['"])src\."#).unwrap();
    re_src
        .replace_all(&content, |caps: &Captures| format!("{}{}.", &caps[1], game_root))
        .into_owned()
}

// ---------------------------------------------------------------- 文件复制

fn ext_of(path: &Path) -> String {
    path.extension()
        .unwrap_or_default()
        .to_string_lossy()
        .to_lowercase()
}

/// 单文件复制：lua 改写模块名；html/css/js 包装为 lua 字符串模块；其余二进制原样
fn transform_and_write(src: &Path, dest: &Path, side: &str, cfg: &BgdConfig) -> Result<bool> {
    let ext = ext_of(src);
    let dest = if TEXT_EXTS.contains(&ext.as_str()) && ext != "lua" {
        dest.with_extension("lua")
    } else {
        dest.to_path_buf()
    };

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }

    if TEXT_EXTS.contains(&ext.as_str()) {
        let content = fs::read_to_string(src)
            .with_context(|| format!("无法读取源文件: {}", src.display()))?;
        let content = if ext == "lua" {
            rewrite_lua(&content, side, cfg)
        } else {
            format!("return [===[{content}]===]")
        };
        fs::write(&dest, content)?;
    } else {
        fs::copy(src, &dest)?;
    }
    Ok(true)
}

fn dest_for(rel: &str, side: &str, code_set: &str, bgd_root: &Path, cfg: &BgdConfig) -> PathBuf {
    let key = format!("{code_set}_{side}_target");
    let target = match key.as_str() {
        "libs_server_target" => &cfg.libs_server_target,
        "libs_client_target" => &cfg.libs_client_target,
        "game_server_target" => &cfg.game_server_target,
        _ => &cfg.game_client_target,
    };
    cfg.abs(bgd_root, target).join(rel.trim_start_matches('/'))
}

fn code_set_dir<'a>(code_set: &str, cfg: &'a BgdConfig) -> (&'a str, &'a [String]) {
    if code_set == "libs" {
        (&cfg.libs_dir, &cfg.libs_excludes)
    } else {
        (&cfg.game_dir, &cfg.game_excludes)
    }
}

/// 构建单个文件，返回产出数量
pub fn build_one_file(
    bgd_root: &Path,
    cfg: &BgdConfig,
    code_set: &str,
    src_abs: &Path,
    log: &LogFn,
) -> Result<usize> {
    let (dir, excludes) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    let rel = format!(
        "/{}",
        src_abs
            .strip_prefix(&src_root)
            .with_context(|| format!("文件不在源目录内: {}", src_abs.display()))?
            .to_string_lossy()
            .replace('\\', "/")
    );

    if is_excluded(&rel, excludes) {
        log(&format!("[skip] excluded: [{code_set}] {rel}"));
        return Ok(0);
    }

    // 入口文件不复制到产物目录（由入口合并流程处理）
    if rel.starts_with("/entrance/") {
        return Ok(0);
    }

    // 资源目录单独处理
    if rel.starts_with("/asset/") {
        return build_asset_file(bgd_root, cfg, code_set, &rel, src_abs, log);
    }

    let sides: Vec<&str> = if rel.starts_with("/server/") {
        vec!["server"]
    } else if rel.starts_with("/client/") {
        vec!["client"]
    } else {
        vec!["server", "client"] // common 双端复制
    };

    let mut count = 0;
    for side in sides {
        let dest = dest_for(&rel, side, code_set, bgd_root, cfg);
        if transform_and_write(src_abs, &dest, side, cfg)? {
            log(&format!("[ok] {side}: [{code_set}] {rel}"));
            count += 1;
        }
    }
    Ok(count)
}

fn build_asset_file(
    bgd_root: &Path,
    cfg: &BgdConfig,
    code_set: &str,
    rel: &str,
    src_abs: &Path,
    log: &LogFn,
) -> Result<usize> {
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(rel, excludes) {
        log(&format!("[skip] asset excluded: [{code_set}] {rel}"));
        return Ok(0);
    }
    let out_name = if code_set == "libs" {
        &cfg.libs_asset_output_name
    } else {
        &cfg.game_asset_output_name
    };
    let rel_out = rel.replacen("/asset", &format!("/{out_name}"), 1);
    let dest = cfg
        .abs(bgd_root, &cfg.asset_target)
        .join(rel_out.trim_start_matches('/'));
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(src_abs, &dest)?;
    log(&format!("[ok] asset: [{code_set}] {rel}"));
    Ok(1)
}

// ---------------------------------------------------------------- API 聚合生成

/// 扫描 {libs,src}/{common,server,client}/api/*.lua，重新生成聚合 init.lua
pub fn regen_api_aggregations(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<Vec<PathBuf>> {
    let mut generated = Vec::new();
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        let root_prefix = Path::new(dir)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        for side in ["common", "server", "client"] {
            let api_dir = src_root.join(side).join("api");
            if !api_dir.is_dir() {
                continue;
            }
            let mut modules: Vec<String> = Vec::new();
            for entry in fs::read_dir(&api_dir)? {
                let entry = entry?;
                let path = entry.path();
                if path.extension().is_some_and(|e| e == "lua")
                    && path.file_name().is_some_and(|n| n != "init.lua")
                {
                    modules.push(path.file_stem().unwrap_or_default().to_string_lossy().into_owned());
                }
            }
            modules.sort();

            let ns = format!("bgd_api.{side}");
            let mut lines = vec![
                API_AGG_HEADER.to_string(),
                format!("-- 全局API聚合：api/ 目录下的每个模块自动挂载为 {ns}.<模块名>"),
            ];
            if code_set == "libs" {
                lines.push(format!("{ns} = {{}}"));
            } else {
                lines.push(format!("{ns} = {ns} or {{}}"));
            }
            for m in &modules {
                lines.push(format!("{ns}.{m} = require('{root_prefix}.{side}.api.{m}')"));
            }
            let out = api_dir.join("init.lua");
            let new_content = format!("{}\n", lines.join("\n"));
            let old = fs::read_to_string(&out).unwrap_or_default();
            if old != new_content {
                fs::write(&out, &new_content)?;
                log(&format!("[gen] api 聚合: {}", out.display()));
            }
            generated.push(out);
        }
    }
    Ok(generated)
}

// ---------------------------------------------------------------- 模板与入口

fn render_template(template_path: &Path, vars: &[(&str, String)]) -> Result<String> {
    let mut content = fs::read_to_string(template_path)?;
    for (key, value) in vars {
        content = content.replace(&format!("{{{{{key}}}}}"), value);
    }
    Ok(content)
}

pub fn process_templates(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let templates_dir = cfg.abs(bgd_root, &cfg.templates_dir);
    for code_set in ["libs", "game"] {
        let tpl = templates_dir.join(format!("init_tp_{code_set}.lua"));
        if !tpl.exists() {
            log(&format!("[warn] 模板不存在: {}", tpl.display()));
            continue;
        }
        for side in ["server", "client"] {
            let key = format!("{code_set}_{side}_target");
            let target_rel = match key.as_str() {
                "libs_server_target" => &cfg.libs_server_target,
                "libs_client_target" => &cfg.libs_client_target,
                "game_server_target" => &cfg.game_server_target,
                _ => &cfg.game_client_target,
            };
            let target = cfg.abs(bgd_root, target_rel);
            let target_name = target
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            let content = render_template(
                &tpl,
                &[
                    ("target", target_name),
                    ("module", side.to_string()),
                    (
                        "time",
                        std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .map(|d| d.as_secs().to_string())
                            .unwrap_or_default(),
                    ),
                ],
            )?;
            fs::create_dir_all(&target)?;
            fs::write(target.join("init.lua"), content)?;
            log(&format!("[ok] {side}: init.lua <- {}", tpl.display()));
        }
    }
    Ok(())
}

pub fn update_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let filename = format!("{kind}.lua");
    let libs_entrance = cfg.abs(bgd_root, &cfg.libs_dir).join("entrance").join(&filename);
    let game_entrance = cfg.abs(bgd_root, &cfg.game_dir).join("entrance").join(&filename);
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);

    let libs_content = fs::read_to_string(&libs_entrance).unwrap_or_default();
    let game_content = fs::read_to_string(&game_entrance).unwrap_or_default();

    let mut merged = libs_content.clone();
    if !game_content.is_empty() {
        if !libs_content.is_empty() {
            merged.push_str("\n\n-- ===== 游戏入口代码 =====\n\n");
        }
        merged.push_str(&game_content);
    }
    if merged.is_empty() {
        merged = format!(
            "-- Auto-generated entrance ({kind})\n-- 请提供框架入口：libs/entrance/{filename}\n-- 或游戏入口：src/entrance/{filename}\n"
        );
    }

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&dest, merged)?;
    log(&format!("[ok] entrance: {kind} -> {}", dest.display()));
    Ok(())
}

// ---------------------------------------------------------------- 全量构建 / 清理

pub fn build_code_set(code_set: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<usize> {
    let (dir, _) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    if !src_root.is_dir() {
        log(&format!("[info] {code_set} 源目录不存在: {}", src_root.display()));
        return Ok(0);
    }
    let mut count = 0;
    for entry in WalkDir::new(&src_root).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() {
            count += build_one_file(bgd_root, cfg, code_set, entry.path(), log)?;
        }
    }
    Ok(count)
}

pub fn build_all(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    log("===== 开始全量构建 =====");
    regen_api_aggregations(bgd_root, cfg, log)?;
    let libs_count = build_code_set("libs", bgd_root, cfg, log)?;
    let game_count = build_code_set("game", bgd_root, cfg, log)?;
    process_templates(bgd_root, cfg, log)?;
    update_entrance("server", bgd_root, cfg, log)?;
    update_entrance("client", bgd_root, cfg, log)?;
    log(&format!(
        "===== 构建完成！框架文件: {libs_count}，游戏文件: {game_count} ====="
    ));
    Ok(())
}

pub fn clean(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    log("===== 清除构建产物 =====");
    for target in [
        &cfg.libs_server_target,
        &cfg.libs_client_target,
        &cfg.game_server_target,
        &cfg.game_client_target,
    ] {
        let abs = cfg.abs(bgd_root, target);
        if abs.is_dir() {
            fs::remove_dir_all(&abs)?;
            log(&format!("  -> 已删除 {}", abs.display()));
        } else {
            log(&format!("  -> 目录不存在，跳过 {}", abs.display()));
        }
    }
    log("===== 清理完成 =====");
    Ok(())
}

/// 清理 .bgd/log 下的 .log 文件，返回删除数量
pub fn clean_logs(bgd_root: &Path, log: &LogFn) -> Result<usize> {
    let log_dir = bgd_root.join("log");
    let mut deleted = 0;
    if log_dir.is_dir() {
        for entry in fs::read_dir(&log_dir)? {
            let path = entry?.path();
            if path.extension().is_some_and(|e| e == "log") {
                fs::remove_file(&path)?;
                deleted += 1;
            }
        }
    }
    log(&format!("日志清理完成，共删除 {deleted} 个 .log 文件"));
    Ok(deleted)
}

// ---------------------------------------------------------------- 监听

fn identify_code_set(path: &Path, bgd_root: &Path, cfg: &BgdConfig) -> Option<&'static str> {
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        if path.starts_with(&src_root) {
            return Some(code_set);
        }
    }
    None
}

fn delete_outputs(path: &Path, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let Some(code_set) = identify_code_set(path, bgd_root, cfg) else {
        return Ok(());
    };
    let (dir, excludes) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    let Ok(rel_path) = path.strip_prefix(&src_root) else {
        return Ok(());
    };
    let rel = format!("/{}", rel_path.to_string_lossy().replace('\\', "/"));
    if is_excluded(&rel, excludes) || rel.starts_with("/entrance/") {
        return Ok(());
    }
    let sides: Vec<&str> = if rel.starts_with("/server/") {
        vec!["server"]
    } else if rel.starts_with("/client/") {
        vec!["client"]
    } else {
        vec!["server", "client"]
    };
    for side in sides {
        let mut dest = dest_for(&rel, side, code_set, bgd_root, cfg);
        let ext = ext_of(&dest);
        if ["html", "css", "js"].contains(&ext.as_str()) {
            dest = dest.with_extension("lua");
        }
        if dest.exists() {
            fs::remove_file(&dest)?;
            log(&format!("[deleted] {side}: [{code_set}] {rel}"));
        }
    }
    Ok(())
}

fn handle_watch_event(event: &Event, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) {
    let mut api_related = false;
    let mut entrance_related = false;

    for path in &event.paths {
        // 只处理文件（目录变更忽略）
        if path.is_dir() {
            continue;
        }
        let path_str = path.to_string_lossy();
        if path_str.contains(format!("{}api{}", std::path::MAIN_SEPARATOR, std::path::MAIN_SEPARATOR).as_str()) {
            api_related = true;
        }
        if path_str.contains("entrance") {
            entrance_related = true;
        }

        match event.kind {
            EventKind::Create(_) | EventKind::Modify(_) => {
                if let Some(code_set) = identify_code_set(path, bgd_root, cfg) {
                    if let Err(e) = build_one_file(bgd_root, cfg, code_set, path, log) {
                        log(&format!("[error] 增量构建失败 {}: {e}", path.display()));
                    }
                }
            }
            EventKind::Remove(_) => {
                if let Err(e) = delete_outputs(path, bgd_root, cfg, log) {
                    log(&format!("[error] 删除产物失败 {}: {e}", path.display()));
                }
            }
            _ => {}
        }
    }

    // api 目录变动：重新生成聚合文件并立即构建
    if api_related {
        if let Ok(gen_files) = regen_api_aggregations(bgd_root, cfg, log) {
            for gen in gen_files {
                if let Some(code_set) = identify_code_set(&gen, bgd_root, cfg) {
                    let _ = build_one_file(bgd_root, cfg, code_set, &gen, log);
                }
            }
        }
    }

    // 入口文件变动：重新合并入口
    if entrance_related {
        let _ = update_entrance("server", bgd_root, cfg, log);
        let _ = update_entrance("client", bgd_root, cfg, log);
    }
}

/// 启动监听（notify 事件驱动）。返回 watcher 句柄，由调用方持有；drop 即停止。
pub fn start_watch<L>(bgd_root: &Path, cfg: &BgdConfig, log: L) -> Result<RecommendedWatcher>
where
    L: Fn(&str) + Send + Sync + 'static,
{
    let bgd_root = bgd_root.to_path_buf();
    let cfg = cfg.clone();
    let log = std::sync::Arc::new(log);

    let log_cb = log.clone();
    let bgd_cb = bgd_root.clone();
    let cfg_cb = cfg.clone();
    let mut watcher = notify::recommended_watcher(move |res: Result<Event, notify::Error>| {
        match res {
            Ok(event) => {
                let log_line = |s: &str| (log_cb)(s);
                handle_watch_event(&event, &bgd_cb, &cfg_cb, &log_line);
            }
            Err(e) => (log_cb)(&format!("[error] 监听事件错误: {e}")),
        }
    })?;

    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, &cfg);
        let src_root = cfg.abs(&bgd_root, dir);
        if src_root.is_dir() {
            watcher.watch(&src_root, RecursiveMode::Recursive)?;
            (log)(&format!("[watch] 正在监听: {}", src_root.display()));
        }
    }
    (log)("[watch] 监听已启动");
    Ok(watcher)
}
