//! 构建核心：全量构建（白名单）、增量构建、清理（入口还原）、API 聚合生成、
//! 根 init.lua 渲染、入口合并（分界标记）、emmyrc/gitignore 合并、文件监听
//! 逻辑与 Python 参考实现（.bgd/tools_py/bgd_build.py）一致。

use crate::config::BgdConfig;
use anyhow::{Context, Result};
use notify::{Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use regex::{Captures, Regex};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

/// 日志回调：构建/监听过程产生的每一行日志
pub type LogFn<'a> = dyn Fn(&str) + Send + 'a;

const TEXT_EXTS: [&str; 4] = ["lua", "html", "css", "js"];
const API_AGG_HEADER: &str = "-- AUTO-GENERATED BY BGD_SCE_TOOLS，请勿手改";
/// 构建输入白名单：code set 根下只有这些子目录进产物流程
const BUILD_SUBDIRS: [&str; 4] = ["server", "client", "common", "asset"];
/// 入口分界标记（标记之后为本工具生成内容）
const ENTRANCE_MARKER: &str =
    "-- ===== AUTO-GENERATED BY bgd_sce_tools（以下内容为入口合并生成，请勿直接编辑） =====";
const GITIGNORE_HEADER: &str =
    "# AUTO-GENERATED BY bgd_sce_tools，请勿手改，请编辑 .bgd/src/.gitignore";

// ---------------------------------------------------------------- 排除规则

/// rel 形如 "/server/GameServer.lua"；排除项如 "types"、"client/eg"（目录边界匹配）
pub fn is_excluded(rel: &str, excludes: &[String]) -> bool {
    let norm = format!("/{}", rel.trim_start_matches('/').replace('\\', "/"));
    for excl in excludes {
        let e = format!("/{}", excl.trim_matches(['/', '\\']).replace('\\', "/"));
        if norm == e || norm.starts_with(&format!("{e}/")) {
            return true;
        }
    }
    false
}

fn in_whitelist(rel: &str) -> bool {
    BUILD_SUBDIRS.iter().any(|d| rel.starts_with(&format!("/{d}/")))
}

// ---------------------------------------------------------------- 模块名改写

/// 把引号内的源码模块名前缀改写为运行时根名：'libs.xxx' -> 'bgd_libs_server.xxx' 等
pub fn rewrite_lua(content: &str, side: &str, cfg: &BgdConfig) -> String {
    let (libs_key, game_key) = if side == "server" {
        (&cfg.libs_server_target, &cfg.game_server_target)
    } else {
        (&cfg.libs_client_target, &cfg.game_client_target)
    };
    let libs_root = Path::new(libs_key)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();
    let game_root = Path::new(game_key)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();

    let re_libs = Regex::new(r#"(['"])libs\."#).unwrap();
    let content = re_libs.replace_all(content, |caps: &Captures| {
        format!("{}{}.", &caps[1], libs_root)
    });
    let re_src = Regex::new(r#"(['"])src\."#).unwrap();
    re_src
        .replace_all(&content, |caps: &Captures| format!("{}{}.", &caps[1], game_root))
        .into_owned()
}

// ---------------------------------------------------------------- 文件复制

fn ext_of(path: &Path) -> String {
    path.extension()
        .unwrap_or_default()
        .to_string_lossy()
        .to_lowercase()
}

/// 单文件复制：lua 改写模块名；html/css/js 包装为 lua 字符串模块；其余二进制原样
fn transform_and_write(src: &Path, dest: &Path, side: &str, cfg: &BgdConfig) -> Result<bool> {
    let ext = ext_of(src);
    let dest = if TEXT_EXTS.contains(&ext.as_str()) && ext != "lua" {
        dest.with_extension("lua")
    } else {
        dest.to_path_buf()
    };

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }

    if TEXT_EXTS.contains(&ext.as_str()) {
        let content = fs::read_to_string(src)
            .with_context(|| format!("无法读取源文件: {}", src.display()))?;
        let content = if ext == "lua" {
            rewrite_lua(&content, side, cfg)
        } else {
            format!("return [===[{content}]===]")
        };
        fs::write(&dest, content)?;
    } else {
        fs::copy(src, &dest)?;
    }
    Ok(true)
}

fn dest_for(rel: &str, side: &str, code_set: &str, bgd_root: &Path, cfg: &BgdConfig) -> PathBuf {
    let key = format!("{code_set}_{side}_target");
    let target = match key.as_str() {
        "libs_server_target" => &cfg.libs_server_target,
        "libs_client_target" => &cfg.libs_client_target,
        "game_server_target" => &cfg.game_server_target,
        _ => &cfg.game_client_target,
    };
    cfg.abs(bgd_root, target).join(rel.trim_start_matches('/'))
}

fn code_set_dir<'a>(code_set: &str, cfg: &'a BgdConfig) -> (&'a str, &'a [String]) {
    if code_set == "libs" {
        (&cfg.libs_dir, &cfg.libs_excludes)
    } else {
        (&cfg.game_dir, &cfg.game_excludes)
    }
}

fn sides_for(rel: &str) -> Vec<&'static str> {
    if rel.starts_with("/server/") {
        vec!["server"]
    } else if rel.starts_with("/client/") {
        vec!["client"]
    } else {
        vec!["server", "client"] // common 双端复制
    }
}

fn rel_of(src_abs: &Path, code_set: &str, bgd_root: &Path, cfg: &BgdConfig) -> Result<String> {
    let (dir, _) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    Ok(format!(
        "/{}",
        src_abs
            .strip_prefix(&src_root)
            .with_context(|| format!("文件不在源目录内: {}", src_abs.display()))?
            .to_string_lossy()
            .replace('\\', "/")
    ))
}

/// 构建单个文件（白名单子目录内），返回产出数量
pub fn build_one_file(
    bgd_root: &Path,
    cfg: &BgdConfig,
    code_set: &str,
    src_abs: &Path,
    log: &LogFn,
) -> Result<usize> {
    let rel = rel_of(src_abs, code_set, bgd_root, cfg)?;
    if !in_whitelist(&rel) {
        return Ok(0);
    }
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(&rel, excludes) {
        log(&format!("[skip] excluded: [{code_set}] {rel}"));
        return Ok(0);
    }

    // 资源目录单独处理
    if rel.starts_with("/asset/") {
        return build_asset_file(bgd_root, cfg, code_set, &rel, src_abs, log);
    }

    let mut count = 0;
    for side in sides_for(&rel) {
        let dest = dest_for(&rel, side, code_set, bgd_root, cfg);
        if transform_and_write(src_abs, &dest, side, cfg)? {
            log(&format!("[ok] {side}: [{code_set}] {rel}"));
            count += 1;
        }
    }
    Ok(count)
}

fn build_asset_file(
    bgd_root: &Path,
    cfg: &BgdConfig,
    code_set: &str,
    rel: &str,
    src_abs: &Path,
    log: &LogFn,
) -> Result<usize> {
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(rel, excludes) {
        log(&format!("[skip] asset excluded: [{code_set}] {rel}"));
        return Ok(0);
    }
    let out_name = if code_set == "libs" {
        &cfg.libs_asset_output_name
    } else {
        &cfg.game_asset_output_name
    };
    let rel_out = rel.replacen("/asset", &format!("/{out_name}"), 1);
    let dest = cfg
        .abs(bgd_root, &cfg.asset_target)
        .join(rel_out.trim_start_matches('/'));
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(src_abs, &dest)?;
    log(&format!("[ok] asset: [{code_set}] {rel}"));
    Ok(1)
}

// ---------------------------------------------------------------- API 聚合生成

/// 扫描 {libs,src}/{common,server,client}/api/*.lua，重新生成聚合 init.lua
pub fn regen_api_aggregations(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<Vec<PathBuf>> {
    let mut generated = Vec::new();
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        let root_prefix = Path::new(dir)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        for side in ["common", "server", "client"] {
            let api_dir = src_root.join(side).join("api");
            if !api_dir.is_dir() {
                continue;
            }
            let mut modules: Vec<String> = Vec::new();
            for entry in fs::read_dir(&api_dir)? {
                let entry = entry?;
                let path = entry.path();
                if path.extension().is_some_and(|e| e == "lua")
                    && path.file_name().is_some_and(|n| n != "init.lua")
                {
                    modules.push(path.file_stem().unwrap_or_default().to_string_lossy().into_owned());
                }
            }
            modules.sort();

            let ns = format!("bgd_api.{side}");
            let mut lines = vec![
                API_AGG_HEADER.to_string(),
                format!("-- 全局API聚合：api/ 目录下的每个模块自动挂载为 {ns}.<模块名>"),
            ];
            if code_set == "libs" {
                lines.push(format!("{ns} = {{}}"));
            } else {
                lines.push(format!("{ns} = {ns} or {{}}"));
            }
            for m in &modules {
                lines.push(format!("{ns}.{m} = require('{root_prefix}.{side}.api.{m}')"));
            }
            let out = api_dir.join("init.lua");
            let new_content = format!("{}\n", lines.join("\n"));
            let old = fs::read_to_string(&out).unwrap_or_default();
            if old != new_content {
                fs::write(&out, &new_content)?;
                log(&format!("[gen] api 聚合: {}", out.display()));
            }
            generated.push(out);
        }
    }
    Ok(generated)
}

// ---------------------------------------------------------------- 根 init.lua 渲染

/// code set 根的 init.lua 作为模板渲染到产物根（{{target}}/{{module}}/{{time}}）
pub fn render_root_init(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let tpl = cfg.abs(bgd_root, dir).join("init.lua");
        if !tpl.exists() {
            log(&format!("[warn] 根 init.lua 不存在: {}", tpl.display()));
            continue;
        }
        let content = fs::read_to_string(&tpl)?;
        for side in ["server", "client"] {
            let key = format!("{code_set}_{side}_target");
            let target_rel = match key.as_str() {
                "libs_server_target" => &cfg.libs_server_target,
                "libs_client_target" => &cfg.libs_client_target,
                "game_server_target" => &cfg.game_server_target,
                _ => &cfg.game_client_target,
            };
            let target = cfg.abs(bgd_root, target_rel);
            let target_name = target
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            let time_str = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs().to_string())
                .unwrap_or_default();
            let out = content
                .replace("{{target}}", &target_name)
                .replace("{{module}}", side)
                .replace("{{time}}", &time_str);
            fs::create_dir_all(&target)?;
            fs::write(target.join("init.lua"), out)?;
            log(&format!("[ok] {side}: init.lua <- {code_set}/init.lua"));
        }
    }
    Ok(())
}

// ---------------------------------------------------------------- 入口合并（分界标记）

/// 原文保留 + 标记 + 框架 entrance + 游戏 entrance。幂等。
pub fn update_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let filename = format!("{kind}.lua");
    let libs_entrance = cfg.abs(bgd_root, &cfg.libs_dir).join("entrance").join(&filename);
    let game_entrance = cfg.abs(bgd_root, &cfg.game_dir).join("entrance").join(&filename);
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);

    // entrance 内容同样要走模块名改写（引号内 libs./src. 前缀 -> 运行时根名）
    let libs_content = rewrite_lua(&fs::read_to_string(&libs_entrance).unwrap_or_default(), kind, cfg);
    let game_content = rewrite_lua(&fs::read_to_string(&game_entrance).unwrap_or_default(), kind, cfg);

    // 提取原文：含标记取标记之前；不含标记则整个现有文件视为原文（首次接入）。
    // 防御：若"原文"自身仍含标记（历史脏数据导致标记堆积），视为损坏，丢弃原文，
    // 让本次构建以空原文重新生成（一次构建即自愈）。
    let mut original = String::new();
    if dest.exists() {
        let existing = fs::read_to_string(&dest).unwrap_or_default();
        let mut candidate = match existing.find(ENTRANCE_MARKER) {
            Some(pos) => existing[..pos].to_string(),
            None => existing,
        };
        if candidate.contains(ENTRANCE_MARKER) {
            log(&format!(
                "[warn] 入口文件检测到残留标记（历史脏数据），已丢弃损坏原文并重建: {}",
                dest.display()
            ));
            candidate = String::new();
        }
        original = candidate;
    }

    let mut generated = libs_content.clone();
    if !game_content.is_empty() {
        if !libs_content.is_empty() {
            generated.push_str("\n\n-- ===== 游戏入口代码 =====\n\n");
        }
        generated.push_str(&game_content);
    }

    let mut parts: Vec<String> = Vec::new();
    if !original.trim().is_empty() {
        parts.push(original.trim_end_matches('\n').to_string());
    }
    parts.push(ENTRANCE_MARKER.to_string());
    if !generated.trim().is_empty() {
        parts.push(generated.trim_end_matches('\n').to_string());
    }
    let merged = format!("{}\n", parts.join("\n\n"));

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&dest, merged)?;
    log(&format!("[ok] entrance: {kind} -> {}", dest.display()));
    Ok(())
}

/// clean 时还原入口：删除标记及之后内容，恢复原文；无标记则不碰
fn restore_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);
    if !dest.exists() {
        return Ok(());
    }
    let existing = fs::read_to_string(&dest).unwrap_or_default();
    if let Some(pos) = existing.find(ENTRANCE_MARKER) {
        fs::write(&dest, &existing[..pos])?;
        log(&format!("  -> 入口已还原: {}", dest.display()));
    }
    Ok(())
}

// ---------------------------------------------------------------- 配置合并生成

/// JSON 深合并：dict 递归；数组并集去重；其余 override 优先
fn deep_merge(base: &Value, over: &Value) -> Value {
    match (base, over) {
        (Value::Object(b), Value::Object(o)) => {
            let mut m = b.clone();
            for (k, v) in o {
                let merged = match m.get(k) {
                    Some(existing) => deep_merge(existing, v),
                    None => v.clone(),
                };
                m.insert(k.clone(), merged);
            }
            Value::Object(m)
        }
        (Value::Array(b), Value::Array(o)) => {
            let mut out = b.clone();
            for item in o {
                if !out.contains(item) {
                    out.push(item.clone());
                }
            }
            Value::Array(out)
        }
        (_, o) => o.clone(),
    }
}

/// libs/.emmyrc.json（base）+ src/.emmyrc.json（override）-> 项目根 .emmyrc.json
pub fn merge_emmyrc(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let libs_f = cfg.abs(bgd_root, &cfg.libs_dir).join(".emmyrc.json");
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join(".emmyrc.json");
    let base: Value = if libs_f.exists() {
        serde_json::from_str(&fs::read_to_string(&libs_f)?).unwrap_or(Value::Null)
    } else {
        Value::Null
    };
    let over: Value = if src_f.exists() {
        serde_json::from_str(&fs::read_to_string(&src_f)?).unwrap_or(Value::Null)
    } else {
        Value::Null
    };
    let merged = deep_merge(&base, &over);
    let out = bgd_root
        .parent()
        .unwrap_or(bgd_root)
        .join(".emmyrc.json");
    fs::write(&out, format!("{}\n", serde_json::to_string_pretty(&merged)?))?;
    log("[ok] merge: .emmyrc.json");
    Ok(())
}

/// libs/.gitignore + src/.gitignore -> 项目根 .gitignore（规则行去重）
pub fn merge_gitignore(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let libs_f = cfg.abs(bgd_root, &cfg.libs_dir).join(".gitignore");
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join(".gitignore");
    let mut sections: Vec<String> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for (title, f) in [("框架规则", libs_f), ("项目规则", src_f)] {
        if !f.exists() {
            continue;
        }
        let mut lines = vec![format!("# ==== {title} ====")];
        for line in fs::read_to_string(&f)?.lines() {
            let key = line.trim();
            let is_rule = !key.is_empty() && !key.starts_with('#');
            if is_rule {
                if seen.contains(key) {
                    continue;
                }
                seen.insert(key.to_string());
            }
            lines.push(line.to_string());
        }
        sections.push(lines.join("\n"));
    }
    let out = bgd_root.parent().unwrap_or(bgd_root).join(".gitignore");
    fs::write(&out, format!("{GITIGNORE_HEADER}\n\n{}\n", sections.join("\n\n")))?;
    log("[ok] merge: .gitignore");
    Ok(())
}

// ---------------------------------------------------------------- 全量构建 / 清理

pub fn build_code_set(code_set: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<usize> {
    let (dir, _) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    if !src_root.is_dir() {
        log(&format!("[info] {code_set} 源目录不存在: {}", src_root.display()));
        return Ok(0);
    }
    let mut count = 0;
    for sub in BUILD_SUBDIRS {
        let subdir = src_root.join(sub);
        if !subdir.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&subdir).into_iter().filter_map(|e| e.ok()) {
            if entry.file_type().is_file() {
                count += build_one_file(bgd_root, cfg, code_set, entry.path(), log)?;
            }
        }
    }
    Ok(count)
}

pub fn build_all(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    log("===== 开始全量构建 =====");
    regen_api_aggregations(bgd_root, cfg, log)?;
    let libs_count = build_code_set("libs", bgd_root, cfg, log)?;
    let game_count = build_code_set("game", bgd_root, cfg, log)?;
    render_root_init(bgd_root, cfg, log)?;
    update_entrance("server", bgd_root, cfg, log)?;
    update_entrance("client", bgd_root, cfg, log)?;
    merge_emmyrc(bgd_root, cfg, log)?;
    merge_gitignore(bgd_root, cfg, log)?;
    log(&format!(
        "===== 构建完成！框架文件: {libs_count}，游戏文件: {game_count} ====="
    ));
    Ok(())
}

pub fn clean(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    log("===== 清除构建产物 =====");
    for target in [
        &cfg.libs_server_target,
        &cfg.libs_client_target,
        &cfg.game_server_target,
        &cfg.game_client_target,
    ] {
        let abs = cfg.abs(bgd_root, target);
        if abs.is_dir() {
            fs::remove_dir_all(&abs)?;
            log(&format!("  -> 已删除 {}", abs.display()));
        } else {
            log(&format!("  -> 目录不存在，跳过 {}", abs.display()));
        }
    }
    restore_entrance("server", bgd_root, cfg, log)?;
    restore_entrance("client", bgd_root, cfg, log)?;
    log("===== 清理完成 =====");
    Ok(())
}

/// 清理 .bgd/log 下的 .log 文件，返回删除数量
pub fn clean_logs(bgd_root: &Path, log: &LogFn) -> Result<usize> {
    let log_dir = bgd_root.join("log");
    let mut deleted = 0;
    if log_dir.is_dir() {
        for entry in fs::read_dir(&log_dir)? {
            let path = entry?.path();
            if path.extension().is_some_and(|e| e == "log") {
                fs::remove_file(&path)?;
                deleted += 1;
            }
        }
    }
    log(&format!("日志清理完成，共删除 {deleted} 个 .log 文件"));
    Ok(deleted)
}

// ---------------------------------------------------------------- 监听

fn identify_code_set(path: &Path, bgd_root: &Path, cfg: &BgdConfig) -> Option<&'static str> {
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        if path.starts_with(&src_root) {
            return Some(code_set);
        }
    }
    None
}

fn delete_outputs(path: &Path, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let Some(code_set) = identify_code_set(path, bgd_root, cfg) else {
        return Ok(());
    };
    let rel = rel_of(path, code_set, bgd_root, cfg)?;
    if !in_whitelist(&rel) {
        return Ok(());
    }
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(&rel, excludes) {
        return Ok(());
    }
    for side in sides_for(&rel) {
        let mut dest = dest_for(&rel, side, code_set, bgd_root, cfg);
        let ext = ext_of(&dest);
        if ["html", "css", "js"].contains(&ext.as_str()) {
            dest = dest.with_extension("lua");
        }
        if dest.exists() {
            fs::remove_file(&dest)?;
            log(&format!("[deleted] {side}: [{code_set}] {rel}"));
        }
    }
    Ok(())
}

/// 监听单文件路由：白名单文件增量构建；根级元文件走专门流程
fn handle_file(path: &Path, deleted: bool, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) {
    let Some(code_set) = identify_code_set(path, bgd_root, cfg) else {
        return;
    };
    let Ok(rel) = rel_of(path, code_set, bgd_root, cfg) else {
        return;
    };

    // 根级 init.lua：模板重渲染
    if rel == "/init.lua" {
        let _ = render_root_init(bgd_root, cfg, log);
        return;
    }
    // 根级 emmyrc/gitignore 片段：重新合并
    if rel == "/.emmyrc.json" {
        let _ = merge_emmyrc(bgd_root, cfg, log);
        return;
    }
    if rel == "/.gitignore" {
        let _ = merge_gitignore(bgd_root, cfg, log);
        return;
    }
    // entrance 文件：重新合并入口
    if rel.starts_with("/entrance/") {
        let _ = update_entrance("server", bgd_root, cfg, log);
        let _ = update_entrance("client", bgd_root, cfg, log);
        return;
    }
    // api 目录变动：重新生成聚合并立即构建
    if rel.contains("/api/") {
        if let Ok(gen_files) = regen_api_aggregations(bgd_root, cfg, log) {
            for gen in gen_files {
                if let Some(gen_set) = identify_code_set(&gen, bgd_root, cfg) {
                    let _ = build_one_file(bgd_root, cfg, gen_set, &gen, log);
                }
            }
        }
    }
    // 普通白名单文件
    if deleted {
        let _ = delete_outputs(path, bgd_root, cfg, log);
    } else {
        let _ = build_one_file(bgd_root, cfg, code_set, path, log);
    }
}

/// 启动监听（notify 事件驱动，带事件去重）。返回 watcher 句柄，由调用方持有；drop 即停止。
///
/// Windows 编辑器保存文件（尤其原子保存）会对一次保存派发多个事件，直接逐事件处理
/// 会产生重复构建/重复日志。这里把同一文件在短时间窗口内的事件聚合为一次：
/// 只要窗口结束时文件仍存在就构建一次，不存在则删除一次。
pub fn start_watch<L>(bgd_root: &Path, cfg: &BgdConfig, log: L) -> Result<RecommendedWatcher>
where
    L: Fn(&str) + Send + Sync + 'static,
{
    use std::collections::HashMap;
    use std::sync::mpsc;
    use std::sync::Arc;
    use std::time::{Duration, Instant};

    const DEBOUNCE_MS: u64 = 300;

    let bgd_root = bgd_root.to_path_buf();
    let cfg = cfg.clone();
    let log = Arc::new(log);

    let (tx, rx) = mpsc::channel::<Event>();
    let mut watcher = notify::recommended_watcher(move |res: Result<Event, notify::Error>| {
        if let Ok(event) = res {
            let _ = tx.send(event);
        }
    })?;

    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, &cfg);
        let src_root = cfg.abs(&bgd_root, dir);
        if src_root.is_dir() {
            watcher.watch(&src_root, RecursiveMode::Recursive)?;
            (log)(&format!("[watch] 正在监听: {}", src_root.display()));
        }
    }
    (log)("[watch] 监听已启动");

    // 后台线程：收集事件并按文件去重后批量处理
    let bgd_cb = bgd_root.clone();
    let cfg_cb = cfg.clone();
    let log_cb = log.clone();
    std::thread::spawn(move || {
        // path -> (deleted, last_seen)
        let mut pending: HashMap<PathBuf, (bool, Instant)> = HashMap::new();
        loop {
            match rx.recv_timeout(Duration::from_millis(DEBOUNCE_MS)) {
                Ok(event) => {
                    for path in event.paths {
                        if path.is_dir() {
                            continue;
                        }
                        let deleted = matches!(event.kind, EventKind::Remove(_));
                        pending
                            .entry(path)
                            .and_modify(|e| {
                                e.0 = deleted;
                                e.1 = Instant::now();
                            })
                            .or_insert((deleted, Instant::now()));
                    }
                }
                Err(mpsc::RecvTimeoutError::Timeout) => {
                    // 处理已静默超过窗口的文件
                    let now = Instant::now();
                    let ready: Vec<PathBuf> = pending
                        .iter()
                        .filter(|(_, (_, t))| now.duration_since(*t) >= Duration::from_millis(DEBOUNCE_MS))
                        .map(|(p, _)| p.clone())
                        .collect();
                    if ready.is_empty() {
                        continue;
                    }
                    let log_line = |s: &str| (log_cb)(s);
                    for path in ready {
                        let (deleted, _) = pending.remove(&path).unwrap_or((false, now));
                        // 最终状态以文件实际存在性为准（避免误删）
                        let actually_deleted = deleted && !path.exists();
                        handle_file(&path, actually_deleted, &bgd_cb, &cfg_cb, &log_line);
                    }
                }
                Err(mpsc::RecvTimeoutError::Disconnected) => break,
            }
        }
    });

    Ok(watcher)
}
