//! 构建核心：全量构建（白名单）、增量构建、清理（入口还原）、API 聚合生成、
//! 根 init.lua 渲染、入口合并（分界标记）、emmyrc/gitignore 合并、文件监听

use crate::config::BgdConfig;
use anyhow::{Context, Result};
use notify::{Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use regex::{Captures, Regex};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

/// 日志回调：构建/监听过程产生的每一行日志
pub type LogFn<'a> = dyn Fn(&str) + Send + 'a;

const TEXT_EXTS: [&str; 4] = ["lua", "html", "css", "js"];
const API_AGG_HEADER: &str = "-- AUTO-GENERATED BY BGD_SCE_TOOLS，请勿手改";
/// 构建输入白名单：code set 根下只有这些子目录进产物流程
const BUILD_SUBDIRS: [&str; 4] = ["server", "client", "common", "res"];
/// 入口分界标记（标记之后为本工具生成内容）
const ENTRANCE_MARKER: &str =
    "-- ===== AUTO-GENERATED BY bgd_sce_tools（以下内容为入口合并生成，请勿直接编辑） =====";
const GITIGNORE_HEADER: &str =
    "# AUTO-GENERATED BY bgd_sce_tools，请勿手改，请编辑 .bgd/src/.gitignore";

// ---------------------------------------------------------------- 监听状态（跨进程共享）

/// 监听状态文件：监听开启时写入，关闭时删除。供 CLI check-watch 跨进程判断。
pub const WATCH_STATE_FILE: &str = ".watch_state.json";

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct WatchState {
    pub pid: u32,
    pub started_at: u64,
    pub project: String,
}

pub fn watch_state_path(bgd_root: &Path) -> PathBuf {
    bgd_root.join(WATCH_STATE_FILE)
}

fn now_ts() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or_default()
}

/// 写入监听状态（监听开启时调用）
pub fn write_watch_state(bgd_root: &Path, project_root: &Path) {
    let state = WatchState {
        pid: std::process::id(),
        started_at: now_ts(),
        project: project_root.to_string_lossy().into_owned(),
    };
    if let Ok(text) = serde_json::to_string_pretty(&state) {
        let _ = fs::write(watch_state_path(bgd_root), text);
    }
}

/// 删除监听状态（监听停止时调用）
pub fn remove_watch_state(bgd_root: &Path) {
    let _ = fs::remove_file(watch_state_path(bgd_root));
}

/// 判断指定 PID 的进程是否为「本工具的监听进程」：存活且映像名与当前 exe 一致
/// （只校 PID 会被 PID 复用误判——状态文件里的旧 PID 可能已被无关进程占用）
fn pid_alive(pid: u32) -> bool {
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        use std::process::Command;
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        let want = std::env::current_exe()
            .ok()
            .and_then(|p| p.file_stem().map(|s| s.to_string_lossy().to_lowercase()))
            .unwrap_or_default();
        if let Ok(out) = Command::new("tasklist")
            .args(["/FI", &format!("PID eq {pid}"), "/NH", "/FO", "CSV"])
            .creation_flags(CREATE_NO_WINDOW)
            .output()
        {
            let stdout = String::from_utf8_lossy(&out.stdout);
            // CSV 首字段为带引号的映像名（如 "bgd_sce_tools.exe"）
            let image = stdout
                .lines()
                .next()
                .and_then(|l| l.split(',').next())
                .unwrap_or("")
                .trim_matches('"')
                .to_lowercase();
            let image = image.trim_end_matches(".exe");
            return !want.is_empty() && image == want;
        }
        false
    }
    #[cfg(not(windows))]
    {
        Path::new(&format!("/proc/{pid}")).exists()
    }
}

/// 查询项目当前是否处于监听中（供 CLI check-watch）。
/// 状态文件存在且 PID 存活且映像名为本工具 => true；否则清理状态文件后 false。
pub fn is_watching(bgd_root: &Path) -> bool {
    let path = watch_state_path(bgd_root);
    let Ok(text) = fs::read_to_string(&path) else {
        return false;
    };
    let Ok(state) = serde_json::from_str::<WatchState>(&text) else {
        return false;
    };
    if pid_alive(state.pid) {
        true
    } else {
        // 上次异常退出未清理，顺手清掉
        let _ = fs::remove_file(&path);
        false
    }
}

// ---------------------------------------------------------------- 排除规则

/// rel 形如 "/server/GameServer.lua"；排除项如 "types"、"client/eg"（目录边界匹配）
pub fn is_excluded(rel: &str, excludes: &[String]) -> bool {
    let norm = format!("/{}", rel.trim_start_matches('/').replace('\\', "/"));
    for excl in excludes {
        let e = format!("/{}", excl.trim_matches(['/', '\\']).replace('\\', "/"));
        if norm == e || norm.starts_with(&format!("{e}/")) {
            return true;
        }
    }
    false
}

fn in_whitelist(rel: &str) -> bool {
    BUILD_SUBDIRS.iter().any(|d| rel.starts_with(&format!("/{d}/")))
}

// ---------------------------------------------------------------- 模块名改写

/// 把引号内的源码模块名前缀改写为运行时根名：'libs.xxx' -> 'bgd_libs_server.xxx' 等
pub fn rewrite_lua(content: &str, side: &str, cfg: &BgdConfig) -> String {
    let (libs_key, game_key) = if side == "server" {
        (&cfg.libs_server_target, &cfg.game_server_target)
    } else {
        (&cfg.libs_client_target, &cfg.game_client_target)
    };
    let libs_root = Path::new(libs_key)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();
    let game_root = Path::new(game_key)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();

    // 'libs.xxx' / 'libs' 两种形式都要改写（裸 require('libs') 加载运行时根）
    let re_libs = Regex::new(r#"(['"])libs(['".])"#).unwrap();
    let content = re_libs.replace_all(content, |caps: &Captures| {
        if &caps[2] == "." {
            format!("{}{}.", &caps[1], libs_root)
        } else {
            format!("{}{}{}", &caps[1], libs_root, &caps[2])
        }
    });
    let re_src = Regex::new(r#"(['"])src(['".])"#).unwrap();
    re_src
        .replace_all(&content, |caps: &Captures| {
            if &caps[2] == "." {
                format!("{}{}.", &caps[1], game_root)
            } else {
                format!("{}{}{}", &caps[1], game_root, &caps[2])
            }
        })
        .into_owned()
}

/// res 资源路径替换：把 'libs/res/<类型>/...' 或 'src/res/<类型>/...' 替换为运行时路径
/// 规则：sound 去掉 .ogg 扩展名，sprites 前缀 @<ProjectName>；各类型固定扩展名 + 资源存在性检查（黄色警告）
fn rewrite_res_paths(content: &str, bgd_root: &Path, _cfg: &BgdConfig, log: &LogFn) -> String {
    let project_name = read_project_name(bgd_root).unwrap_or_else(|_| "unknown".to_string());
    let project_root = bgd_root.parent().unwrap_or(bgd_root);
    let mut result = content.to_string();
    let mut warnings: Vec<String> = Vec::new();

    for code_set in ["libs", "src"] {
        for res_type in ["image", "particle", "sound", "spine", "sprites"] {
            let pattern = format!(r#"['"]({code_set}/res/{res_type}/[^'"]+)['"]"#);
            let re = Regex::new(&pattern).unwrap();
            result = re
                .replace_all(&result, |caps: &Captures| {
                    let full_path = &caps[1]; // libs/res/image/armor_dark.png
                    let rel_path = full_path
                        .trim_start_matches(&format!("{code_set}/res/{res_type}/"));
                    let (new_path, warn) = rewrite_single_res_path(
                        code_set, res_type, rel_path, &project_name, project_root,
                    );
                    if let Some(w) = warn {
                        warnings.push(w);
                    }
                    format!("'{new_path}'")
                })
                .into_owned();
        }
    }

    // 输出黄色警告（构建日志流）
    for w in warnings {
        log(&format!("[warn] {w}"));
    }

    result
}

/// 重写单个 res 路径，返回 (新路径, 可选警告)
fn rewrite_single_res_path(
    code_set: &str,
    res_type: &str,
    rel_path: &str,
    project_name: &str,
    project_root: &Path,
) -> (String, Option<String>) {
    let prefix = if code_set == "libs" { "bgd_libs_client" } else { "bgd_game_client" };
    let base = project_root.join(".bgd").join(code_set).join("res").join(res_type);

    match res_type {
        "image" => {
            let name = rel_path.trim_end_matches(".png");
            let file = base.join(format!("{name}.png"));
            let warn = if !file.exists() {
                Some(format!("资源不存在: {code_set}/res/image/{rel_path}（期望 .png）"))
            } else {
                None
            };
            (format!("image/image/{prefix}/{name}.png"), warn)
        }
        "particle" => {
            let name = rel_path.trim_end_matches(".effect");
            let file = base.join(format!("{name}.effect"));
            let warn = if !file.exists() {
                Some(format!("资源不存在: {code_set}/res/particle/{rel_path}（期望 .effect）"))
            } else {
                None
            };
            (format!("res/effect/{prefix}/{name}.effect"), warn)
        }
        "sound" => {
            let name = rel_path.trim_end_matches(".ogg");
            let file = base.join(format!("{name}.ogg"));
            let warn = if !file.exists() {
                Some(format!("资源不存在: {code_set}/res/sound/{rel_path}（期望 .ogg）"))
            } else {
                None
            };
            (format!("res/sound/{prefix}/{name}"), warn)
        }
        "spine" => {
            let name = rel_path.trim_end_matches(".skel");
            let file = base.join(format!("{name}.skel"));
            let warn = if !file.exists() {
                Some(format!("资源不存在: {code_set}/res/spine/{rel_path}（期望 .skel）"))
            } else {
                None
            };
            (format!("spine/{prefix}/{name}"), warn)
        }
        "sprites" => {
            // sprites：目录无扩展名，文件保留扩展名
            let path = base.join(rel_path);
            let (name, ext) = if path.is_dir() {
                (rel_path.to_string(), String::new())
            } else {
                match path.extension() {
                    Some(e) => (
                        rel_path.trim_end_matches(&format!(".{}", e.to_string_lossy())).to_string(),
                        format!(".{}", e.to_string_lossy()),
                    ),
                    None => (rel_path.to_string(), String::new()),
                }
            };
            let warn = if !path.exists() {
                Some(format!("资源不存在: {code_set}/res/sprites/{rel_path}"))
            } else {
                None
            };
            (format!("@{project_name}/image/sprites/{prefix}/{name}{ext}"), warn)
        }
        _ => (rel_path.to_string(), None),
    }
}

// ---------------------------------------------------------------- 文件复制

fn ext_of(path: &Path) -> String {
    path.extension()
        .unwrap_or_default()
        .to_string_lossy()
        .to_lowercase()
}

/// 单文件复制：lua 改写模块名；html/css/js 包装为 lua 字符串模块；其余二进制原样
fn transform_and_write(src: &Path, dest: &Path, side: &str, cfg: &BgdConfig, bgd_root: &Path, log: &LogFn) -> Result<bool> {
    let ext = ext_of(src);
    let dest = if TEXT_EXTS.contains(&ext.as_str()) && ext != "lua" {
        dest.with_extension("lua")
    } else {
        dest.to_path_buf()
    };

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }

    if TEXT_EXTS.contains(&ext.as_str()) {
        let content = fs::read_to_string(src)
            .with_context(|| format!("无法读取源文件: {}", src.display()))?;
        let content = if ext == "lua" {
            let content = rewrite_lua(&content, side, cfg);
            rewrite_res_paths(&content, bgd_root, cfg, log)
        } else {
            format!("return [===[{content}]===]")
        };
        fs::write(&dest, content)?;
    } else {
        fs::copy(src, &dest)?;
    }
    Ok(true)
}

fn dest_for(rel: &str, side: &str, code_set: &str, bgd_root: &Path, cfg: &BgdConfig) -> PathBuf {
    let key = format!("{code_set}_{side}_target");
    let target = match key.as_str() {
        "libs_server_target" => &cfg.libs_server_target,
        "libs_client_target" => &cfg.libs_client_target,
        "game_server_target" => &cfg.game_server_target,
        _ => &cfg.game_client_target,
    };
    cfg.abs(bgd_root, target).join(rel.trim_start_matches('/'))
}

fn code_set_dir<'a>(code_set: &str, cfg: &'a BgdConfig) -> (&'a str, &'a [String]) {
    if code_set == "libs" {
        (&cfg.libs_dir, &cfg.libs_excludes)
    } else {
        (&cfg.game_dir, &cfg.game_excludes)
    }
}

fn sides_for(rel: &str) -> Vec<&'static str> {
    if rel.starts_with("/server/") {
        vec!["server"]
    } else if rel.starts_with("/client/") {
        vec!["client"]
    } else {
        vec!["server", "client"] // common 双端复制
    }
}

fn rel_of(src_abs: &Path, code_set: &str, bgd_root: &Path, cfg: &BgdConfig) -> Result<String> {
    let (dir, _) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    Ok(format!(
        "/{}",
        src_abs
            .strip_prefix(&src_root)
            .with_context(|| format!("文件不在源目录内: {}", src_abs.display()))?
            .to_string_lossy()
            .replace('\\', "/")
    ))
}

/// 构建单个文件（白名单子目录内），返回产出数量
pub fn build_one_file(
    bgd_root: &Path,
    cfg: &BgdConfig,
    code_set: &str,
    src_abs: &Path,
    log: &LogFn,
) -> Result<usize> {
    let rel = rel_of(src_abs, code_set, bgd_root, cfg)?;
    if !in_whitelist(&rel) {
        return Ok(0);
    }
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(&rel, excludes) {
        log(&format!("[skip] excluded: [{code_set}] {rel}"));
        return Ok(0);
    }

    // res 资源目录：.lua 不同步（它是代码），其余资源文件同步到引擎目录
    if rel.starts_with("/res/") {
        if ext_of(src_abs) == "lua" {
            return Ok(0);
        }
        return sync_res_file(bgd_root, cfg, code_set, &rel, src_abs, log);
    }

    let mut count = 0;
    for side in sides_for(&rel) {
        let dest = dest_for(&rel, side, code_set, bgd_root, cfg);
        if transform_and_write(src_abs, &dest, side, cfg, bgd_root, log)? {
            log(&format!("[ok] {side}: [{code_set}] {rel}"));
            count += 1;
        }
    }
    Ok(count)
}

// ---------------------------------------------------------------- res 资源同步

/// res 资源类型 -> 引擎目标子路径（相对项目根）
/// image/particle/sound/spine/sprites 五类，前缀按 code_set 区分
fn res_target_subdir(res_type: &str, code_set: &str) -> Option<String> {
    let prefix = if code_set == "libs" { "bgd_libs_client" } else { "bgd_game_client" };
    match res_type {
        "image" => Some(format!("ui/image/image/{prefix}")),
        "particle" => Some(format!("res/effect/{prefix}")),
        "sound" => Some(format!("res/sound/{prefix}")),
        "spine" => Some(format!("ui/spine/{prefix}")),
        "sprites" => Some(format!("ui/image/sprites/{prefix}")),
        _ => None,
    }
}

/// 同步单个 res 资源文件到引擎目录（二进制原样复制）
fn sync_res_file(
    bgd_root: &Path,
    cfg: &BgdConfig,
    code_set: &str,
    rel: &str,
    src_abs: &Path,
    log: &LogFn,
) -> Result<usize> {
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(rel, excludes) {
        log(&format!("[skip] res excluded: [{code_set}] {rel}"));
        return Ok(0);
    }
    // rel 形如 /res/<type>/<path...>
    let parts: Vec<&str> = rel.trim_start_matches('/').splitn(3, '/').collect();
    if parts.len() < 3 {
        return Ok(0);
    }
    let res_type = parts[1];
    let sub_path = parts[2];
    let Some(target_sub) = res_target_subdir(res_type, code_set) else {
        log(&format!("[warn] 未知资源类型: [{code_set}] {rel}"));
        return Ok(0);
    };
    let project_root = bgd_root.parent().unwrap_or(bgd_root);
    let dest = project_root.join(&target_sub).join(sub_path);
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(src_abs, &dest)?;
    log(&format!("[ok] res: [{code_set}] {rel} -> {target_sub}/{sub_path}"));
    Ok(1)
}

// ---------------------------------------------------------------- res 清单生成

/// 从 map_settings.json 读取 ProjectName（sprites 路径前缀用）
fn read_project_name(bgd_root: &Path) -> Result<String> {
    let project_root = bgd_root.parent().unwrap_or(bgd_root);
    let path = project_root.join("project").join("map_settings.json");
    let text = fs::read_to_string(&path)
        .with_context(|| format!("无法读取地图配置: {}", path.display()))?;
    let json: serde_json::Value = serde_json::from_str(&text)?;
    json["ProjectName"]
        .as_str()
        .map(|s| s.to_string())
        .ok_or_else(|| anyhow::anyhow!("map_settings.json 缺少 ProjectName"))
}

// ---------------------------------------------------------------- API 聚合生成

/// 扫描 {libs,src}/{common,server,client}/api/*.lua，重新生成聚合 init.lua
pub fn regen_api_aggregations(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<Vec<PathBuf>> {
    let mut generated = Vec::new();
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        let root_prefix = Path::new(dir)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        for side in ["common", "server", "client"] {
            let api_dir = src_root.join(side).join("api");
            if !api_dir.is_dir() {
                continue;
            }
            let mut modules: Vec<String> = Vec::new();
            for entry in fs::read_dir(&api_dir)? {
                let entry = entry?;
                let path = entry.path();
                if path.extension().is_some_and(|e| e == "lua")
                    && path.file_name().is_some_and(|n| n != "init.lua")
                {
                    modules.push(path.file_stem().unwrap_or_default().to_string_lossy().into_owned());
                }
            }
            modules.sort();

            let ns = format!("bgd_api.{side}");
            let mut lines = vec![
                API_AGG_HEADER.to_string(),
                format!("-- 全局API聚合：api/ 目录下的每个模块自动挂载为 {ns}.<模块名>"),
            ];
            if code_set == "libs" {
                lines.push(format!("{ns} = {{}}"));
            } else {
                lines.push(format!("{ns} = {ns} or {{}}"));
            }
            for m in &modules {
                lines.push(format!("{ns}.{m} = require('{root_prefix}.{side}.api.{m}')"));
            }
            let out = api_dir.join("init.lua");
            let new_content = format!("{}\n", lines.join("\n"));
            let old = fs::read_to_string(&out).unwrap_or_default();
            if old != new_content {
                fs::write(&out, &new_content)?;
                log(&format!("[gen] api 聚合: {}", out.display()));
            }
            generated.push(out);
        }
    }
    Ok(generated)
}

// ---------------------------------------------------------------- 根 init.lua 渲染

/// code set 根的 init.lua 作为模板渲染到产物根（{{target}}/{{module}}/{{time}}）
pub fn render_root_init(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let tpl = cfg.abs(bgd_root, dir).join("init.lua");
        if !tpl.exists() {
            log(&format!("[warn] 根 init.lua 不存在: {}", tpl.display()));
            continue;
        }
        let content = fs::read_to_string(&tpl)?;
        for side in ["server", "client"] {
            let key = format!("{code_set}_{side}_target");
            let target_rel = match key.as_str() {
                "libs_server_target" => &cfg.libs_server_target,
                "libs_client_target" => &cfg.libs_client_target,
                "game_server_target" => &cfg.game_server_target,
                _ => &cfg.game_client_target,
            };
            let target = cfg.abs(bgd_root, target_rel);
            let target_name = target
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .into_owned();
            let time_str = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs().to_string())
                .unwrap_or_default();
            let out = content
                .replace("{{target}}", &target_name)
                .replace("{{module}}", side)
                .replace("{{time}}", &time_str);
            fs::create_dir_all(&target)?;
            fs::write(target.join("init.lua"), out)?;
            log(&format!("[ok] {side}: init.lua <- {code_set}/init.lua"));
        }
    }
    Ok(())
}

// ---------------------------------------------------------------- 入口合并（分界标记）

/// 原文保留 + 标记 + 框架 entrance + 游戏 entrance。幂等。
pub fn update_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let filename = format!("{kind}.lua");
    let libs_entrance = cfg.abs(bgd_root, &cfg.libs_dir).join("entrance").join(&filename);
    let game_entrance = cfg.abs(bgd_root, &cfg.game_dir).join("entrance").join(&filename);
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);

    // entrance 内容同样要走模块名改写（引号内 libs./src. 前缀 -> 运行时根名）
    let libs_content = rewrite_lua(&fs::read_to_string(&libs_entrance).unwrap_or_default(), kind, cfg);
    let game_content = rewrite_lua(&fs::read_to_string(&game_entrance).unwrap_or_default(), kind, cfg);

    // 提取原文：含标记取标记之前；不含标记则整个现有文件视为原文（首次接入）。
    // 防御：若"原文"自身仍含标记（历史脏数据导致标记堆积），视为损坏，丢弃原文，
    // 让本次构建以空原文重新生成（一次构建即自愈）。
    let mut original = String::new();
    if dest.exists() {
        let existing = fs::read_to_string(&dest).unwrap_or_default();
        let mut candidate = match existing.find(ENTRANCE_MARKER) {
            Some(pos) => existing[..pos].to_string(),
            None => existing,
        };
        if candidate.contains(ENTRANCE_MARKER) {
            log(&format!(
                "[warn] 入口文件检测到残留标记（历史脏数据），已丢弃损坏原文并重建: {}",
                dest.display()
            ));
            candidate = String::new();
        }
        original = candidate;
    }

    let mut generated = libs_content.clone();
    if !game_content.is_empty() {
        if !libs_content.is_empty() {
            generated.push_str("\n\n-- ===== 游戏入口代码 =====\n\n");
        }
        generated.push_str(&game_content);
    }

    let mut parts: Vec<String> = Vec::new();
    if !original.trim().is_empty() {
        parts.push(original.trim_end_matches('\n').to_string());
    }
    parts.push(ENTRANCE_MARKER.to_string());
    if !generated.trim().is_empty() {
        parts.push(generated.trim_end_matches('\n').to_string());
    }
    let merged = format!("{}\n", parts.join("\n\n"));

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&dest, merged)?;
    log(&format!("[ok] entrance: {kind} -> {}", dest.display()));
    Ok(())
}

/// clean 时还原入口：删除标记及之后内容，恢复原文；无标记则不碰
fn restore_entrance(kind: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let dest_rel = if kind == "server" {
        &cfg.server_entrance
    } else {
        &cfg.client_entrance
    };
    let dest = cfg.abs(bgd_root, dest_rel);
    if !dest.exists() {
        return Ok(());
    }
    let existing = fs::read_to_string(&dest).unwrap_or_default();
    if let Some(pos) = existing.find(ENTRANCE_MARKER) {
        fs::write(&dest, &existing[..pos])?;
        log(&format!("  -> 入口已还原: {}", dest.display()));
    }
    Ok(())
}

// ---------------------------------------------------------------- 配置合并生成

/// JSON 深合并：dict 递归；数组并集去重；其余 override 优先
fn deep_merge(base: &Value, over: &Value) -> Value {
    match (base, over) {
        (Value::Object(b), Value::Object(o)) => {
            let mut m = b.clone();
            for (k, v) in o {
                let merged = match m.get(k) {
                    Some(existing) => deep_merge(existing, v),
                    None => v.clone(),
                };
                m.insert(k.clone(), merged);
            }
            Value::Object(m)
        }
        (Value::Array(b), Value::Array(o)) => {
            let mut out = b.clone();
            for item in o {
                if !out.contains(item) {
                    out.push(item.clone());
                }
            }
            Value::Array(out)
        }
        (_, o) => o.clone(),
    }
}

/// libs/.emmyrc.json（base）+ src/.emmyrc.json（override）-> 项目根 .emmyrc.json
pub fn merge_emmyrc(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let libs_f = cfg.abs(bgd_root, &cfg.libs_dir).join(".emmyrc.json");
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join(".emmyrc.json");
    let base: Value = if libs_f.exists() {
        serde_json::from_str(&fs::read_to_string(&libs_f)?).unwrap_or(Value::Null)
    } else {
        Value::Null
    };
    let over: Value = if src_f.exists() {
        serde_json::from_str(&fs::read_to_string(&src_f)?).unwrap_or(Value::Null)
    } else {
        Value::Null
    };
    let merged = deep_merge(&base, &over);
    let out = bgd_root
        .parent()
        .unwrap_or(bgd_root)
        .join(".emmyrc.json");
    fs::write(&out, format!("{}\n", serde_json::to_string_pretty(&merged)?))?;
    log("[ok] merge: .emmyrc.json");
    Ok(())
}

/// libs/.gitignore + src/.gitignore -> 项目根 .gitignore（规则行去重）
pub fn merge_gitignore(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let libs_f = cfg.abs(bgd_root, &cfg.libs_dir).join(".gitignore");
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join(".gitignore");
    let mut sections: Vec<String> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for (title, f) in [("框架规则", libs_f), ("项目规则", src_f)] {
        if !f.exists() {
            continue;
        }
        let mut lines = vec![format!("# ==== {title} ====")];
        for line in fs::read_to_string(&f)?.lines() {
            let key = line.trim();
            let is_rule = !key.is_empty() && !key.starts_with('#');
            if is_rule {
                if seen.contains(key) {
                    continue;
                }
                seen.insert(key.to_string());
            }
            lines.push(line.to_string());
        }
        sections.push(lines.join("\n"));
    }
    let out = bgd_root.parent().unwrap_or(bgd_root).join(".gitignore");
    fs::write(&out, format!("{GITIGNORE_HEADER}\n\n{}\n", sections.join("\n\n")))?;
    log("[ok] merge: .gitignore");
    Ok(())
}

/// src/AGENTS.md -> 项目根 AGENTS.md（与 .gitignore 同策略：构建产物，要改就改 .bgd/src/AGENTS.md）
/// 源不存在则不动根文件；内容一致则跳过写入（避免监听触发无意义刷盘）
pub fn sync_agents_md(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let src_f = cfg.abs(bgd_root, &cfg.game_dir).join("AGENTS.md");
    if !src_f.exists() {
        return Ok(());
    }
    let out = bgd_root.parent().unwrap_or(bgd_root).join("AGENTS.md");
    let content = fs::read(&src_f)?;
    if out.exists() && fs::read(&out)? == content {
        return Ok(());
    }
    fs::write(&out, content)?;
    log("[ok] sync: AGENTS.md <- src/AGENTS.md");
    Ok(())
}

// ---------------------------------------------------------------- 全量构建 / 清理

pub fn build_code_set(code_set: &str, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<usize> {
    let (dir, _) = code_set_dir(code_set, cfg);
    let src_root = cfg.abs(bgd_root, dir);
    if !src_root.is_dir() {
        log(&format!("[info] {code_set} 源目录不存在: {}", src_root.display()));
        return Ok(0);
    }
    let mut count = 0;
    for sub in BUILD_SUBDIRS {
        let subdir = src_root.join(sub);
        if !subdir.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&subdir).into_iter().filter_map(|e| e.ok()) {
            if entry.file_type().is_file() {
                count += build_one_file(bgd_root, cfg, code_set, entry.path(), log)?;
            }
        }
    }
    Ok(count)
}

pub fn build_all(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    log("===== 开始全量构建 =====");
    regen_api_aggregations(bgd_root, cfg, log)?;
    let libs_count = build_code_set("libs", bgd_root, cfg, log)?;
    let game_count = build_code_set("game", bgd_root, cfg, log)?;
    render_root_init(bgd_root, cfg, log)?;
    update_entrance("server", bgd_root, cfg, log)?;
    update_entrance("client", bgd_root, cfg, log)?;
    merge_emmyrc(bgd_root, cfg, log)?;
    merge_gitignore(bgd_root, cfg, log)?;
    sync_agents_md(bgd_root, cfg, log)?;
    log(&format!(
        "===== 构建完成！框架文件: {libs_count}，游戏文件: {game_count} ====="
    ));
    Ok(())
}

pub fn clean(bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    log("===== 清除构建产物 =====");
    for target in [
        &cfg.libs_server_target,
        &cfg.libs_client_target,
        &cfg.game_server_target,
        &cfg.game_client_target,
    ] {
        let abs = cfg.abs(bgd_root, target);
        if abs.is_dir() {
            fs::remove_dir_all(&abs)?;
            log(&format!("  -> 已删除 {}", abs.display()));
        } else {
            log(&format!("  -> 目录不存在，跳过 {}", abs.display()));
        }
    }
    restore_entrance("server", bgd_root, cfg, log)?;
    restore_entrance("client", bgd_root, cfg, log)?;
    clean_res_files(bgd_root, log)?;
    log("===== 清理完成 =====");
    Ok(())
}

/// 清除同步到引擎目录的资源文件（ui/image/、res/effect/ 等下的 bgd_* 目录）
fn clean_res_files(bgd_root: &Path, log: &LogFn) -> Result<()> {
    let project_root = bgd_root.parent().unwrap_or(bgd_root);
    for code_set in ["libs", "game"] {
        let prefix = if code_set == "libs" { "bgd_libs_client" } else { "bgd_game_client" };
        for sub in [
            format!("ui/image/image/{prefix}"),
            format!("res/effect/{prefix}"),
            format!("res/sound/{prefix}"),
            format!("ui/spine/{prefix}"),
            format!("ui/image/sprites/{prefix}"),
        ] {
            let path = project_root.join(&sub);
            if path.is_dir() {
                fs::remove_dir_all(&path)?;
                log(&format!("  -> 已删除资源 {sub}"));
            }
        }
    }
    Ok(())
}

/// 清理 .bgd/log 下的 .log 文件，返回删除数量
pub fn clean_logs(bgd_root: &Path, log: &LogFn) -> Result<usize> {
    let log_dir = bgd_root.join("log");
    let mut deleted = 0;
    if log_dir.is_dir() {
        for entry in fs::read_dir(&log_dir)? {
            let path = entry?.path();
            if path.extension().is_some_and(|e| e == "log") {
                fs::remove_file(&path)?;
                deleted += 1;
            }
        }
    }
    log(&format!("日志清理完成，共删除 {deleted} 个 .log 文件"));
    Ok(deleted)
}

// ---------------------------------------------------------------- 监听

fn identify_code_set(path: &Path, bgd_root: &Path, cfg: &BgdConfig) -> Option<&'static str> {
    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, cfg);
        let src_root = cfg.abs(bgd_root, dir);
        if path.starts_with(&src_root) {
            return Some(code_set);
        }
    }
    None
}

fn delete_outputs(path: &Path, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) -> Result<()> {
    let Some(code_set) = identify_code_set(path, bgd_root, cfg) else {
        return Ok(());
    };
    let rel = rel_of(path, code_set, bgd_root, cfg)?;
    if !in_whitelist(&rel) {
        return Ok(());
    }
    let (_, excludes) = code_set_dir(code_set, cfg);
    if is_excluded(&rel, excludes) {
        return Ok(());
    }
    for side in sides_for(&rel) {
        let mut dest = dest_for(&rel, side, code_set, bgd_root, cfg);
        let ext = ext_of(&dest);
        if ["html", "css", "js"].contains(&ext.as_str()) {
            dest = dest.with_extension("lua");
        }
        if dest.exists() {
            fs::remove_file(&dest)?;
            log(&format!("[deleted] {side}: [{code_set}] {rel}"));
        }
    }
    Ok(())
}

/// 监听单文件路由：白名单文件增量构建；根级元文件走专门流程
fn handle_file(path: &Path, deleted: bool, bgd_root: &Path, cfg: &BgdConfig, log: &LogFn) {
    let Some(code_set) = identify_code_set(path, bgd_root, cfg) else {
        return;
    };
    let Ok(rel) = rel_of(path, code_set, bgd_root, cfg) else {
        return;
    };

    // 根级 init.lua：模板重渲染
    if rel == "/init.lua" {
        let _ = render_root_init(bgd_root, cfg, log);
        return;
    }
    // 根级 emmyrc/gitignore 片段：重新合并
    if rel == "/.emmyrc.json" {
        let _ = merge_emmyrc(bgd_root, cfg, log);
        return;
    }
    if rel == "/.gitignore" {
        let _ = merge_gitignore(bgd_root, cfg, log);
        return;
    }
    // src/AGENTS.md：同步到项目根
    if rel == "/AGENTS.md" && code_set == "game" {
        let _ = sync_agents_md(bgd_root, cfg, log);
        return;
    }
    // entrance 文件：重新合并入口
    if rel.starts_with("/entrance/") {
        let _ = update_entrance("server", bgd_root, cfg, log);
        let _ = update_entrance("client", bgd_root, cfg, log);
        return;
    }
    // api 目录变动：重新生成聚合并立即构建
    if rel.contains("/api/") {
        if let Ok(gen_files) = regen_api_aggregations(bgd_root, cfg, log) {
            for gen in gen_files {
                if let Some(gen_set) = identify_code_set(&gen, bgd_root, cfg) {
                    let _ = build_one_file(bgd_root, cfg, gen_set, &gen, log);
                }
            }
        }
    }
    // 普通白名单文件
    if deleted {
        let _ = delete_outputs(path, bgd_root, cfg, log);
    } else {
        let _ = build_one_file(bgd_root, cfg, code_set, path, log);
    }
}

/// 启动监听（notify 事件驱动，带事件去重）。返回 watcher 句柄，由调用方持有；drop 即停止。
///
/// Windows 编辑器保存文件（尤其原子保存）会对一次保存派发多个事件，直接逐事件处理
/// 会产生重复构建/重复日志。这里把同一文件在短时间窗口内的事件聚合为一次：
/// 只要窗口结束时文件仍存在就构建一次，不存在则删除一次。
pub fn start_watch<L>(bgd_root: &Path, cfg: &BgdConfig, log: L) -> Result<RecommendedWatcher>
where
    L: Fn(&str) + Send + Sync + 'static,
{
    use std::collections::HashMap;
    use std::sync::mpsc;
    use std::sync::Arc;
    use std::time::{Duration, Instant};

    const DEBOUNCE_MS: u64 = 300;

    let bgd_root = bgd_root.to_path_buf();
    let cfg = cfg.clone();
    let log = Arc::new(log);

    let (tx, rx) = mpsc::channel::<Event>();
    let mut watcher = notify::recommended_watcher(move |res: Result<Event, notify::Error>| {
        if let Ok(event) = res {
            let _ = tx.send(event);
        }
    })?;

    for code_set in ["libs", "game"] {
        let (dir, _) = code_set_dir(code_set, &cfg);
        let src_root = cfg.abs(&bgd_root, dir);
        if src_root.is_dir() {
            watcher.watch(&src_root, RecursiveMode::Recursive)?;
            (log)(&format!("[watch] 正在监听: {}", src_root.display()));
        }
    }
    (log)("[watch] 监听已启动");

    // 后台线程：收集事件并按文件去重后批量处理
    let bgd_cb = bgd_root.clone();
    let cfg_cb = cfg.clone();
    let log_cb = log.clone();
    std::thread::spawn(move || {
        // path -> (deleted, last_seen)
        let mut pending: HashMap<PathBuf, (bool, Instant)> = HashMap::new();
        loop {
            match rx.recv_timeout(Duration::from_millis(DEBOUNCE_MS)) {
                Ok(event) => {
                    for path in event.paths {
                        if path.is_dir() {
                            continue;
                        }
                        let deleted = matches!(event.kind, EventKind::Remove(_));
                        pending
                            .entry(path)
                            .and_modify(|e| {
                                e.0 = deleted;
                                e.1 = Instant::now();
                            })
                            .or_insert((deleted, Instant::now()));
                    }
                }
                Err(mpsc::RecvTimeoutError::Timeout) => {
                    // 处理已静默超过窗口的文件
                    let now = Instant::now();
                    let ready: Vec<PathBuf> = pending
                        .iter()
                        .filter(|(_, (_, t))| now.duration_since(*t) >= Duration::from_millis(DEBOUNCE_MS))
                        .map(|(p, _)| p.clone())
                        .collect();
                    if ready.is_empty() {
                        continue;
                    }
                    let log_line = |s: &str| (log_cb)(s);
                    for path in ready {
                        let (deleted, _) = pending.remove(&path).unwrap_or((false, now));
                        // 最终状态以文件实际存在性为准（避免误删）
                        let actually_deleted = deleted && !path.exists();
                        handle_file(&path, actually_deleted, &bgd_cb, &cfg_cb, &log_line);
                    }
                }
                Err(mpsc::RecvTimeoutError::Disconnected) => break,
            }
        }
    });

    Ok(watcher)
}
